global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics/backend'
    scrape_interval: 15s

  - job_name: 'ml-service'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics/ml'
    scrape_interval: 15s
